// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDodlHjLmSATuLMrTz2wITP4PlrqeMYbvQ',
    appId: '1:753534868301:web:f1809fd3dcc0c6d56df504',
    messagingSenderId: '753534868301',
    projectId: 'court-click-6d9ef',
    authDomain: 'court-click-6d9ef.firebaseapp.com',
    storageBucket: 'court-click-6d9ef.firebasestorage.app',
    measurementId: 'G-4Y6HGV1SWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAijXNtYTWPIeoSTx7qRq3sxEDMSYQMwS0',
    appId: '1:753534868301:android:9b3b8aed75b3bbc06df504',
    messagingSenderId: '753534868301',
    projectId: 'court-click-6d9ef',
    storageBucket: 'court-click-6d9ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_mas2j5qxPNPK08dKt5zra3CyImVLZdc',
    appId: '1:753534868301:ios:f277cb7d05a927d46df504',
    messagingSenderId: '753534868301',
    projectId: 'court-click-6d9ef',
    storageBucket: 'court-click-6d9ef.firebasestorage.app',
    iosBundleId: 'com.courtclick.moviediscapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_mas2j5qxPNPK08dKt5zra3CyImVLZdc',
    appId: '1:753534868301:ios:c506f55304c965216df504',
    messagingSenderId: '753534868301',
    projectId: 'court-click-6d9ef',
    storageBucket: 'court-click-6d9ef.firebasestorage.app',
    iosBundleId: 'com.example.courtClickMovieDicoveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDodlHjLmSATuLMrTz2wITP4PlrqeMYbvQ',
    appId: '1:753534868301:web:034a1d067c2847466df504',
    messagingSenderId: '753534868301',
    projectId: 'court-click-6d9ef',
    authDomain: 'court-click-6d9ef.firebaseapp.com',
    storageBucket: 'court-click-6d9ef.firebasestorage.app',
    measurementId: 'G-V0CCLC8W7E',
  );
}
